-- NUMBER OF POSTS AND AVG LENGTH OF POST BETWEEN 24/10 AND NOW
SELECT ROUND(AVG(CHAR_LENGTH(content)), 2) AS AVG_POST_LENGTH, COUNT(*) AS Nº_OF_POSTS 
FROM `post`
WHERE posted_at BETWEEN '2024-10-24' AND NOW();
