-- NUMBER OF POSTS AND AVG LENGTH OF POST BETWEEN 24/10 AND NOW
SELECT ROUND(AVG(CHAR_LENGTH(content)), 2) AS AVG_POST_LENGTH, COUNT(*) AS Nº_OF_POSTS 
FROM `post`
WHERE posted_at BETWEEN '2024-10-24' AND NOW();
-- USERNAME AND EMAIL OF ALL USERS WHO HAVE POSTED IN THE LAST 7 DAYS
SELECT C.username, C.email, P.*
FROM `posts` AS P 
JOIN chitter_users AS C ON C.user_id = P.user_id
WHERE posted_at IN (CURDATE() AND SUBDATE(CURDATE(), INTERVAL 7 DAY));
